# Generated by Django 5.1.4 on 2024-12-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(),
        ),
    ]
